### ISSUE TITLE
Can't upload new package

### ISSUE THREAD

**Issue by alexpogue** [lasote/conan-sdl2#1]
I want to upload to conan.io a package that I built from source using `conan install SDL2/2.0.3@lasote/stable --build SDL2`. The build succeeds and the package shows up in `conan search`. When I try to upload using `conan upload SDL2/2.0.3@lasote/stable --all` and enter username and password, I get "ERROR: Unauthorized". I have verified that I am able to submit packages to conan.io by following the docs to submit `Hello/0.1@apogue/testing`.

I built the package from source because there is no existing binaries for my configuration - OS X El Capitan using clang 7.3. I'm a Conan newcomer, so it's possible I don't understand how it works or whether this is expected behavior when you try uploading packages to someone else's package recipe.

**Comment by lasote** [comment]
Hi @alexpogue!
I didn't upload SDL2 packages because we detect some problems with compiled packages (we thing something is linked with drivers/gl/system stuff) and it's not working well changing the computer. So we prefer to not upload binary packages for SDL2. 

So, you cannot upload to  `SDL2/2.0.3@lasote/stable` because only "lasote" user is able to write there. 
 If you want your packages ready for your environment just upload them to a channel in your username namespace.
You can take a look to "conan copy" command to change the user/channel of a package. You could do:

`conan copy SDL2/2.0.3@lasote/stable apogue/stable
 conan upload SDL2/2.0.3@apogue/stable`

And then use SDL2/2.0.3@apogue/stable in all your packages.

FYI: In the next months we will prepare a permissions system that will allow to grant read/write access to repositories.
